#!/bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2012 OmniTI Computer Consulting, Inc.  All rights reserved.
# Copyright 2018 OmniOS Community Edition (OmniOSce) Association.
#

. /lib/svc/share/smf_include.sh
. /lib/svc/share/initial_include.sh

if [ -e "/.initialboot" ]; then
	SCRIPT=`/bin/mktemp`
	echo "#!/bin/sh" > $SCRIPT
	echo ". /lib/svc/share/smf_include.sh" >> $SCRIPT
	echo ". /lib/svc/share/initial_include.sh" >> $SCRIPT
	cat /.initialboot >> $SCRIPT
	chmod 550 $SCRIPT
	echo "Applying initial boot settings..." | tee /dev/msglog
	$SCRIPT
	rv=$?
	if [ "$rv" != "$SMF_EXIT_OK" ]; then
		exit $rv
	fi
	rm -f /.initialboot
else
	/usr/sbin/svcadm disable $SMF_FMRI
fi

exit $SMF_EXIT_OK

