#!/bin/ksh
#
# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END
#
# Copyright 2019 OmniOS Community Edition (OmniOSce) Association.
#

[ -f /lib/svc/share/smf_include.sh ] || exit 1

. /lib/svc/share/smf_include.sh

_path=`grep '^PATH=' /etc/default/login | sed -n '
    s/PATH=//
    p
    q
    '`

[ -z "$_path" ] && _path=/usr/sbin:/usr/bin

# Man -w uses the PATH to determine where to look for man pages.
export PATH=$_path
/usr/bin/man -w

exit 0
